### ISSUE TITLE
Plugin fails

### ISSUE THREAD

**Issue by microtherion** [Jozott00/drone-gitea-message#1]
Does the `.md` file need any particular structure?
```
time="2024-06-24T01:58:46Z" level=info msg="Start message commenting" pr.index=1 repo.baseurl="http://git.aereperennius.org/" repo.name=woodshedin repo.owner=microtherion
time="2024-06-24T01:58:46Z" level=info msg="Start deletion of PR comments" deleteIdentifier=test-report-delete-id
time="2024-06-24T01:58:46Z" level=info msg="Found comments with identifier: 0"
time="2024-06-24T01:58:46Z" level=info msg="Deletion of old comment(s) completed" numberOfComments=0
time="2024-06-24T01:58:46Z" level=info msg="Sending message as PR comment..."
time="2024-06-24T01:58:46Z" level=fatal msg="json: cannot unmarshal array into Go value of type gitea.Comment"
```

**Comment by microtherion** [comment]
This turned out to be a silly error on my part: I had given a `http:` URL for my repo. My server redirects this to the corresponding `https:` URL, and it appears that this redirect is being followed for `GET` requests but not `POST` requests.

**Comment by microtherion** [comment]
That said, the way the Gitea SDK reports this problem is anything but ideal, but I don't think there's anything you can do about it.

**Comment by Jozott00** [comment]
Glad to see that you have solved the problem! Yes, this error report is unfortunately very cryptic ...
